# Generated by Django 4.0.3 on 2022-10-17 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Context',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=200)),
                ('time', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('network', models.CharField(max_length=200)),
                ('bluetooth', models.CharField(max_length=200)),
            ],
        ),
    ]
