# Generated by Django 4.1.2 on 2022-11-17 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Context", "0002_task_delete_context"),
    ]

    operations = [
        migrations.CreateModel(
            name="Key",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key_name", models.CharField(max_length=100)),
            ],
        ),
    ]
